{% set version = '4.1-13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpart
  version: {{ version|replace("-", "_") }}

source:
  fn: rpart_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rpart_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rpart/rpart_{{ version }}.tar.gz
  sha256: 8e11a6552224e0fbe23a85aba95acd21a0889a3fe48277f3d345de3147c7494c

build:
  merge_build_host: True  # [win]
  number: 1002

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('rpart')"           # [not win]
    - "\"%R%\" -e \"library('rpart')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rpart
  license: GPL-2 | GPL-3
  summary: Recursive partitioning for classification,  regression and survival trees.  An implementation
    of most of the  functionality of the 1984 book by Breiman, Friedman, Olshen and
    Stone.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - dbast
